spring:
  application:
    name: catalog-service
  datasource:
    driver-class-name: com.mongodb.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/catalog-service.sql
    username: root
    password: root
  sql:
    init:
      mode: always
      data-locations: classpath:/catalog-service.sql
  jpa:
    deferDatasourceInitialization: true
    hibernate:
      ddlAuto: create-drop