spring:

  application:
    name: serie-service
  spring:
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    data:
      mongodb:
        authentication-database: admin
        database: catalog
        port: 27017
        host: localhost

