server:
  port: 8083

application:
  name: catalog-service
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      host: catalog-database
      database: catalog_database
      port: 27019
      username: series
      password: series



eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10


info:
  app:
    description: Catalog service
    version: 1.0.0