server:
  port: 8082


spring:
  application:
    name: serie-service
  security:
     oauth2:
       resourceserver:
         jwt:
           issuer-uri: https://accounts.google.com
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      host: series-database
      database: series_database
      port: 27017
      username: series
      password: series



eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10


info:
  app:
    description: Series service
    version: 1.0.0